### ISSUE TITLE
依赖貌似没写全

### ISSUE THREAD

**Issue by shenmo7192** [linuxdeepin/deepin-terminal#1]
执行两个指令之后make依然报错，百度得是缺少libreadline-dev

**Comment by BLumia** [comment]
现在的维护团队没更新 README 吧，最下面还放着我的免责声明呢...

构建依赖可以参考 https://github.com/linuxdeepin/deepin-terminal-reborn/blob/master/debian/control 这个，另如果你在 deepin 下的话，可以考虑使用 `apt build-dep 包名` 来装构建依赖。

**Comment by felixonmars** [comment]
在 deb 系以外的话可以参考 Arch 的：https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/deepin-terminal

**Comment by shenmo7192** [comment]
> 
> 
> 在 deb 系以外的话可以参考 Arch 的：https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/deepin-terminal

千真万确我用的deepin 20

**Comment by BLumia** [comment]
Arch 竟然也换 DTK 版终端了，印象里在 Deepin 社区版还没正式发布 - -

qtermwidget 的 patch 可以考虑推给上游，就不用 vendor 了（

**Comment by felixonmars** [comment]
@BLumia 嗯，现在在 Arch [community-testing]。qtermwidget 的 patch 不好推的，改得又多又乱，还特地把名字改了……

**Comment by BLumia** [comment]
看上去 https://github.com/linuxdeepin/deepin-terminal-reborn/commit/04136f0fcf8c983645e1a48da763ba7a898836cf 中已处理了这个问题。
