### ISSUE TITLE
Menu white text against white background.

### ISSUE THREAD

**Issue by marvinroman** [linuxdeepin/deepin-terminal#100]
OS: Pop!_OS 21.04
Desktop Theme: Dark

I am not sure when it occurred and thought I would be able to fix later when I had time. Unfortunately that was months ago and now that I am looking into it I haven't found where the issue is coming from.
What I have tried.

- Resetting to default settings in Deepin Terminal.
- Changing Desktop Theme for PopOS to Light.
- Trying different themes within Deepin Terminal.
- Re-installing Deepin Terminal. 

It's only a slight inconvenience since as I hover over items in the menus they are slightly darker so that I can read them.
Here are some screenshots.

![Right Click Menu](https://user-images.githubusercontent.com/341606/136710818-907b8957-392d-4762-be13-898cbf559e00.png)
![Application Menu](https://user-images.githubusercontent.com/341606/136710814-28f9c11d-3a94-459f-a427-a26426986d41.png)

**Comment by ovidenov** [comment]
+1, I am facing exactly the same issue.

**Comment by ch593030323** [comment]
It looks like u are using deepin-terminal-gtk. Please tell me the version of terminal.
If deepin-terminal-gtk is used, i suggest the deepin-terminal from "https://github.com/linuxdeepin/deepin-terminal"

**Comment by Sky-Asher** [comment]
Thank you for your support. This issue will be closed soon.
