### ISSUE TITLE
Can't use arrow keys in python console

### ISSUE THREAD

**Issue by mfocqueteau** [linuxdeepin/deepin-terminal#107]
In the python console I can't use the arrow keys to move the cursor left and right to change something written in that line. I also can't use up and down arrow keys to browse the past inputs. All I get when I press them is stuff like `^[[D^[[A^[[C^[[B`.

Expected behavior:
- Left and right arrow keys should move the cursor without making changes to the line.
- Up and down arrow keys should cycle through previous entries.

(basically how it is in bash)

**Comment by ch593030323** [comment]
in deepin-terminal 5.4.15, i try that "Left and right" and "Up and down" are both OK as u told.
please to paste  some images or videos of the issue here.

**Comment by mfocqueteau** [comment]
Sorry for the troubles, I was trying it out in a VM and that seems to be the issue. It's working fine in the live environment.
