### ISSUE TITLE
Seems didn't source ~/.zprofile when open a new terminal

### ISSUE THREAD

**Issue by mmqmzk** [linuxdeepin/deepin-terminal#11]
OS: ubuntu 20.04.
deepin-terminal/focal,now 5.0.0+ds1-1 amd64 installed from apt.

My default shell is ZSH, it's is ok when I open gnome-terminal. 
I can't find any configurations in Deepin terminal settings.
Does deepin terminal default open the login shell, or did I miss something?

**Comment by z966768** [comment]
Temporarily did not add this default shell setting

**Comment by lfom** [comment]
@mmqmzk 

1. I think the package you have from Ubuntu 20.04 is actually the older (deprecated) version: https://github.com/linuxdeepin/deepin-terminal-old

2. I am not sure why I had to do this, but it works here: I have all my settings in **.profile** (so they work with bash), and then I have a **.zprofile** with this single line:
`emulate sh -c 'source ~/.profile'`

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
