### ISSUE TITLE
【建议】远程连接ssh服务器后，可以支持文件管理。

### ISSUE THREAD

**Issue by MicroOps-cn** [linuxdeepin/deepin-terminal#115]
现在的上传下载只能依赖rz/sz，在选择文件/路径的时候很不方便，希望能支持像xshell、MobaXterm那种的直接打开一个窗口/区域进行文件操作，可以将远程、本地互相拖拽复制，当然如果支持一个远程到另一个远程的拖拽复制那更好了。

另外还建议在打开的文件管理器中直接调用本地的文件编辑器编辑文件

**Comment by ch593030323** [comment]
感谢您的建议
个人而言，终端更倾向于命令操作，而不是界面操作
像远程拖拽复制、远程文件管理等，有更加专业的工具可以完成

**Comment by MicroOps-cn** [comment]
> 感谢您的建议 个人而言，终端更倾向于命令操作，而不是界面操作 像远程拖拽复制、远程文件管理等，有更加专业的工具可以完成

你的想法很合理, 
主要是我看到终端现在支持上传和下载功能,但是我使用起来感觉并不好用, 必须得安装lrzsz. 
当然你说的远程文件管理使用更加专业的工具来完成,这个也很对, 但是这样的话,我得又要多在一个软件上管理我的登陆配置(帐号/密码等信息), 如果服务器数量少倒问题不大,但是上百台服务器, 管理起来还是有点麻烦,
而且我的工作电脑和家用电脑上要实现同步,也是一个麻烦事. 
之前我在windows下面使用keepass+xshell+xftp, keepass管理密码/同步密码 ,xshell命令行管理服务器, xftp管理文件, 总体来说很方便,所以我一直在找能替代这种模式的linux下的工具,

**Comment by MicroOps-cn** [comment]
这个也只是我的个人需求, 这个建议的确和现在deepin-terminal的发展方向不太符合.

**Comment by ch593030323** [comment]
多谢你的理解
上面提到的场景在正常工作中会经常用到，但这不是一个终端就能解决的事
