### ISSUE TITLE
Quake mode query

### ISSUE THREAD

**Issue by jaitra1264** [linuxdeepin/deepin-terminal#117]
So I've been using yakuake as my terminal, its a retractable terminal. I was wondering if the quake mode on deepin-terminal had similar functionality. If so please reply with it.

**Comment by ch593030323** [comment]
if u meaning"a drop-down terminal"，the quake-mode of deepin-terminal can meet u.

**Comment by ch593030323** [comment]
In UOS-Linux system, the shortcut "Alt+F2" is set for the quake-mode, but other system maybe not working fine

**Comment by jaitra1264** [comment]
I am on Kubuntu and alt + f2 didn't work and fn + f2 brins up rename tab option

**Comment by ch593030323** [comment]
In Kubuntu, u can add custom-shortcuts like the following.
![image](https://user-images.githubusercontent.com/10093841/150928889-17b5fc4d-bb17-4f5f-8468-3822277b7a53.png)
