### ISSUE TITLE
编译依赖错误

### ISSUE THREAD

**Issue by JX-Zhang98** [linuxdeepin/deepin-terminal#12]
Ubuntu 18.04 x64
使用```sudo apt build-dep .```检查依赖通过，但cmake过程中出现以下问题：
dtkgui缺失；dtk-settings-tools缺失。
```
➜  build git:(master) sudo apt build-dep ..
注意，正使用 '..' 目录下载编译依赖
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
下列软件包是自动安装的并且现在不需要了：
  deepin-menu expect libqt5svg5-dev libqt5xdg-dev libqt5xdgiconloader-dev libtcl8.6 tcl-expect tcl8.6
使用'sudo apt autoremove'来卸载它(它们)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 536 个软件包未被升级。
➜  build git:(master) cmake ..             
-- Checking for one of the modules 'dtkgui'
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:645 (message):
  None of the required 'dtkgui' found
Call Stack (most recent call first):
  CMakeLists.txt:55 (pkg_search_module)


-- Keyboard layouts will be installed in: /usr/share/terminalwidget5/kb-layouts
-- Color schemes will be installed in: /usr/share/terminalwidget5/color-schemes
-- Translations will be installed in: /usr/share/terminalwidget5/translations
dtk-settings-tools could not be found at /dtk-settings
-- Configuring incomplete, errors occurred!
See also "/home/jx/Desktop/deepin-terminal/build/CMakeFiles/CMakeOutput.log".
```
不知道是不是由于libdtkwidget-dev(>=5.1.0)版本不够导致的

-------------------------
*另外想知道在哪里切换中英文，看到有中文语言包，但是编译结果二进制中没有找到切换语言按钮*
Thank you~

**Comment by BLumia** [comment]
>   None of the required 'dtkgui' found

看看本地有没有 `libdtkgui-dev` 这个包吧。

**Comment by JX-Zhang98** [comment]
> 看看本地有没有 `libdtkgui-dev` 这个包吧。

没有的，但是使用apt安装时```E: 无法定位软件包 libdtkgui-dev```

**Comment by JX-Zhang98** [comment]
经过升级环境后，仍然存在之前的问题。。。

```
 jx@ubuntu  ~/Desktop/deepin-terminal/build   master  sudo apt-get install libdtkwidget-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
libdtkwidget-dev 已经是最新版 (2.0.7.2-2build1)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 7 个软件包未被升级。
 jx@ubuntu  ~/Desktop/deepin-terminal/build   master  cd .. && sudo apt build-dep .
注意，正使用 '.' 目录下载编译依赖
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 7 个软件包未被升级。
 jx@ubuntu  ~/Desktop/deepin-terminal   master  cd build && cmake ..
-- Checking for one of the modules 'dtkgui'
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:645 (message):
  None of the required 'dtkgui' found
Call Stack (most recent call first):
  CMakeLists.txt:55 (pkg_search_module)


-- Keyboard layouts will be installed in: /usr/share/terminalwidget5/kb-layouts
-- Color schemes will be installed in: /usr/share/terminalwidget5/color-schemes
-- Translations will be installed in: /usr/share/terminalwidget5/translations
dtk-settings-tools could not be found at /dtk-settings
-- Configuring incomplete, errors occurred!
See also "/home/jx/Desktop/deepin-terminal/build/CMakeFiles/CMakeOutput.log".

```
但是libdtkwidget-dev只能搞到2.0.7.2版本的，不知道会不会是这个的原因

**Comment by BLumia** [comment]
对哦，您是 Ubuntu 18.04 x64，那您就得先构建和安装前置依赖才能继续构建这个项目了。这个 DTK 版终端的项目基于 dtk5，您得先构建和安装 dtk5 才可以，不过我不太清楚目前 dtk 对 Deepin/UOS 和 Arch 之外的发行版的支持情况 = =||

**Comment by JX-Zhang98** [comment]
那么想问一下您还能找到比较新的支持dtk2的commit吗，我上一次构建的时候是成功的，尽管在Ubuntu中不能使用背景模糊。回退几个版本应该是能比较简单的构建的。但是在commit记录里我没找到相关的信息

**Comment by BLumia** [comment]
> 我上一次构建的时候是成功的

不太清楚上次构建的时间是什么时候了，如果上次构建比较早的话，你可能在用的并不是 DTK 版本而是 [GTK 版本](https://github.com/linuxdeepin/deepin-terminal-old)？

因为这个项目其实一开始就是基于 DTK5 的了，DTK2 的版本是初期还没立项的时候的版本了，几乎没什么功能的，可以见[这里](https://github.com/BLumia/deepin-terminal-ng/tree/v15-dtkwidget2)。

**Comment by JX-Zhang98** [comment]
> 你可能在用的并不是 DTK 版本而是 GTK 版本？

你是对的。。我终于找到了之前使用的commit id，它属于deepin terminal old。

-------  
另外我想知道GTK版本是否有相关的编译选项来选择编译目标使用的语言
谢谢~

**Comment by BLumia** [comment]
> GTK版本是否有相关的编译选项来选择编译目标使用的语言

编译目标所使用的语言是指？

GTK/vala 版本的终端没有提供什么额外的支持，目前可选的应该就只有是否使用 vendor 库了。也可以看 old 对应 repo 的 README 或者 CMakeLists.txt，另外 old 相关的问题也建议在 old 对应的 repo 开 issue :)

**Comment by JX-Zhang98** [comment]
非常感谢耐心的解答，基本已经解决了，使用了old构建成功。
本repo的内容对于Ubuntu受限于DTK仍然不太好弄

**Comment by BLumia** [comment]
> 本repo的内容对于Ubuntu受限于DTK仍然不太好弄

得看 dtk 团队对非 deepin/arch 的发行版的支持计划了。我也不是很清楚目前这类的计划。 cc @xmuli

**Comment by XMuli** [comment]
其他发行版本的也有支持, 目前`最好可能是 ArchLinux, 其他发行版也支持, 但是有些具体的可能还是覆盖不很全面；其中 openEuler 和 [UbuntuDDE](https://ubuntudde.com/) (这个你应该会感兴趣)

**Comment by JX-Zhang98** [comment]
非常感谢各位大神为deepin推广做的贡献，基本没啥问题啦
> UbuntuDDE (这个你应该会感兴趣)

被导师催着开始干活了，就不折腾了，转向了Macbuntu+deepin terminal，足够漂亮到提高工作效率啦
