### ISSUE TITLE
unset不起作用

### ISSUE THREAD

**Issue by jay763190097** [linuxdeepin/deepin-terminal#13]
![截图录屏_选择区域_20200713133405](https://user-images.githubusercontent.com/16317178/87274463-6997ee00-c50e-11ea-858c-3e7234402cd1.png)
![截图录屏_选择区域_20200713133317](https://user-images.githubusercontent.com/16317178/87274473-6c92de80-c50e-11ea-9296-f865593f5d48.png)
```bash
jay@jay-PC:~$ setproxy
jay@jay-PC:~$ curl -I www.google.com.hk
HTTP/1.1 200 OK
content-type: text/html; charset=Big5
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
date: Sat, 15 Aug 2020 09:11:06 GMT
server: gws
x-xss-protection: 0
x-frame-options: SAMEORIGIN
set-cookie: 1P_JAR=2020-08-15-09; expires=Mon, 14-Sep-2020 09:11:06 GMT; path=/; domain=.google.com.hk; Secure
set-cookie: NID=204=xbLQdoTg-0VxkUiezGvpQ1lbP0LspviG8K-7wMsFko5AlyfRk62ErwzbkUbHou9Xiv-UxaL5ue8DrrYNkqGC8wEIVLZ8zg14C2XgU8_tZYEtPfhDPTQZ8fk0VNh_7HF5jw5v5LFGqWMKf-l00YSzf4bWi9lWIL2wu8Vez77jckY; expires=Sun, 14-Feb-2021 09:11:06 GMT; path=/; domain=.google.com.hk; HttpOnly
expires: Sat, 15 Aug 2020 09:11:06 GMT
cache-control: private
content-length: 0

jay@jay-PC:~$ unsetproxy
jay@jay-PC:~$ curl -I www.google.com.hk
curl: (7) Failed to connect to www.google.com.hk port 80: 连接超时

```

**Comment by z966768** [comment]
First, this is a linux command, the terminal is only called and displayed,second, this command is effective here. so I suggest you check your system

**Comment by jay763190097** [comment]
@z966768 I don't think so. Because I compare two terminal tool, deepin-terminal didn't work well.

**Comment by z966768** [comment]
@jay763190097 Can you show what shell the two terminals use

**Comment by jay763190097** [comment]
@z966768 You can look at the first comment,In the picture,you can see the shell.
And I have known what's the problem since I tried to uncheck use-proxy in the right-click menu. It's the same result between deepin-terminal and other terminal tools right now. Thank you!
![截图录屏_选择区域_20200815171531](https://user-images.githubusercontent.com/16317178/90309482-86fc1580-df1b-11ea-87f5-cccd61a12ab3.png)
