### ISSUE TITLE
[Manjaro] some main functions doesn't work

### ISSUE THREAD

**Issue by avently** [linuxdeepin/deepin-terminal#17]
I waited until development will not be on early stages so now it's time to open issues I think. Tell me if I'm wrong and the terminal is on early stages of development.
After I installed new terminal via `sudo pacman -U /path-to-file/` (I'm on Manjaro) I got the terminal with some non-working functions. Take a look at the screenrecord:
[screenrecord-terminal.zip](https://github.com/linuxdeepin/deepin-terminal/files/5033262/screenrecord-terminal.zip)

Here is a list:
- icons don't show up on tabs, in settings
- inability to select a font because all of them are missing
- impossible to change a theme even if I can select them in menu
- fullscreen tabs not always can be viewed. Sometimes they just don't want to react on mouse move to the top of a window
- color theme is unreedable (yellow color on while).

**Comment by felixonmars** [comment]
Currently DDE apps don't work well in other desktop environments. @xmuli We probably should track this whole problem as a issue.

**Comment by linlinzhao** [comment]
One thing I really like about DDE is its terminal comes with tons of color themes. But since last update, this functionality has gone. Will recompiling the terminal from source help with that?

**Comment by felixonmars** [comment]
> One thing I really like about DDE is its terminal comes with tons of color themes. But since last update, this functionality has gone. Will recompiling the terminal from source help with that?

Unfortunately no. They promised to add it back but they are slow on this.

**Comment by XMuli** [comment]
@felixonmars @Linlinzhao I have seen this suggestion many times. The team of the new terminal is developing a new theme (they have adopted it in the planning), but in fact, I feel that the progress of the theme is a bit slow (may be related to other function development)

**Comment by linlinzhao** [comment]
Glad to hear this is in the planning. I cannot tolerate the current looking of the terminal which is not customizable, so switched to gnome terminal for the moment.

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
