### ISSUE TITLE
[bug] Quake terminal doesn't close when lost focus Ubuntu

### ISSUE THREAD

**Issue by maxjf1** [linuxdeepin/deepin-terminal#19]
Quake terminal (properly configured) doesn't close when lost focus. In fact, it doesn't automatically gain focus when open.

Steps to reproduce: 

1 - Open an normal deepin terminal.
2 - Open an quake terminal `deepin-terminal -q` (or using an shortcut)
3 - the deepin terminal will not gain focus (when typing, it will insert on the normal terminal)
4 - When clicking other place, it will not close. You will need to click it to focus and then click out

System info:

```bash
                          ./+o+-       maxjf1@maxjf1-G3-3579
                  yyyyy- -yyyyyy+      OS: Ubuntu 20.04 focal
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.4.0-42-generic
           .++ .:/++++++/-.+sss/`      Uptime: 2h 31m
         .:++o:  /++++++++/:--:/-      Packages: 1947
        o:+o+:++.`..```.-/oo+++++/     Shell: zsh 5.8
       .:+o:+o/.          `+sssoo+/    Resolution: 1920x1080
  .++/+:+oo+o:`             /sssooo.   DE: GNOME 3.36.2
 /+++//+:`oo+o               /::--:.   WM: Mutter
 \+/+o+++`o++o               ++////.   WM Theme: Adwaita
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Mojave-dark [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: McMojave-circle-dark
        \+.++o+o``-````.:ohdhhhhh+     Font: Garuda 11
         `:o+++ `ohhhhhhhhyo++os:      Disk: 51G / 79G (68%)
           .o:`.syhhhhhhh/.oo++o`      CPU: Intel Core i5-8300H @ 8x 4GHz [52.0°C]
               /osyyyyyyo++ooo+++/     GPU: Intel Corporation UHD Graphics 630 (Mobile)
                   ````` +oo+++o\:     RAM: 5092MiB / 15858MiB
                          `oo++.      

```

**Comment by YutianGe** [comment]
In Settings, you can set to hide terminal Windows after losing focus

**Comment by maxjf1** [comment]
> In Settings, you can set to hide terminal Windows after losing focus

@YutianGe I have this setting on of course. and i've noticed an pattern: the first time it opens, it gains focus normally (and when click elsewhere it lost focus and hides normally). but in the second time it is opened, it doesn't work properly.

See record below (notice when i click).
![deepin-screen-recorder_Select area_20210517123926](https://user-images.githubusercontent.com/6114888/118516750-fc944c80-b70c-11eb-832b-5d029872fec5.gif)

My settings:
![image](https://user-images.githubusercontent.com/6114888/118517146-585ed580-b70d-11eb-9c1f-00b5369f7ce0.png)

**Comment by YutianGe** [comment]
What's your version? Try the Upgrade Version
