### ISSUE TITLE
[feature] Recognize clickable link

### ISSUE THREAD

**Issue by maxjf1** [linuxdeepin/deepin-terminal#20]
Would be an great feature to recognize clickable links, just like other terminals does.

If possible, give instructions where on the project it should be implemented (i will try to get involved to contribute)

![image](https://user-images.githubusercontent.com/6114888/89904245-0fe31c00-dbbf-11ea-9cb0-bb6303356e95.png)

**Comment by z966768** [comment]
please try newest version
