### ISSUE TITLE
4K分辨率下无法修改与删除远程管理的远程服务器

### ISSUE THREAD

**Issue by sanxiHsu** [linuxdeepin/deepin-terminal#21]
OS version：deepin v20 beta
application version：5.0.4.1
screen：4K
problem：经本人实测，terminal在1080P分辨率可正常添加、修改、删除远程管理里面的服务器；
4K分辨率下适配有问题，点击右边修改图标时会直接连接而不是修改。

**Comment by z966768** [comment]
老终端已经停止维护,可以尝试使用新版终端
