### ISSUE TITLE
The screen division is broken

### ISSUE THREAD

**Issue by aqvador** [linuxdeepin/deepin-terminal#23]
When I try to divide the terminal into remote servers,
Throws it to the local console.
on deepon 15 everything worked perfectly from the box(

Remote Host:
root@lk:/var/www/mySites# expect -f /tmp/deepin-terminal-5QMTP0
bash: expect: команда не найдена

Local:
achelnokov@pc:~$ deepin-terminal --version
Deepin Terminal 5.0.4.1
Copyright 2011-2017 Deepin, Inc.

achelnokov@pc:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Deepin
Description:	Deepin 20
Release:	20
Codename:	n/a

**Comment by aqvador** [comment]
The latest update did not solve the problem of splitting screens on the remote server.
All the same, when splitting screens, I get to the local console =(
v 5.2.11

Plus removed the design themes, the green console is not happy at all. it became even worse to live with deepin

**Comment by z966768** [comment]
This is an old version of the terminal, maintenance has been stopped, please try with the new version
