### ISSUE TITLE
[Question] About terminal themes

### ISSUE THREAD

**Issue by Duke1715** [linuxdeepin/deepin-terminal#24]
Why in deepin-terminal 5.2.11-1 you have a desigin to remove themes? For now its realy uncomfortable to use only dark\lite themes. Can you have a chance to return themes in next updates?

**Comment by xjtu-blacksmith** [comment]
One more thing: the default light theme seems to work badly with Vim's default color scheme ...

In dark theme, some of the contents were in white color:

![图片](https://user-images.githubusercontent.com/42454373/94152411-1945f080-feae-11ea-8fe5-e107abe3363d.png)

while they were still white in light theme and then *disappeared* ...

![图片](https://user-images.githubusercontent.com/42454373/94152430-206cfe80-feae-11ea-8758-e6ade516cc90.png)

**Comment by z966768** [comment]
Thank you for your suggestions, collected

**Comment by nanoant** [comment]
I agree with @Duke1715 the ability to select other themes from `/usr/share/terminalwidget5/color-schemes` is needed, also with some option to select user themes. Right now only way to have anything else than `Dark.colorscheme` is to override the file inside `/usr/share/terminalwidget5/color-schemes`.

**Comment by dacevedo12** [comment]
Any update on this? I'm kinda getting tired of the green text

**Comment by nanoant** [comment]
> Any update on this? I'm kinda getting tired of the green text

@dacevedo12 You can override `Dark.colorscheme` in `/usr/share/terminalwidget5/color-schemes` with other colorscheme of you choice. It is manual process but it works.

**Comment by Duke1715** [comment]
[deepin-terminal-themes.zip](https://github.com/linuxdeepin/deepin-terminal/files/5542493/deepin-terminal-themes.zip)
@dacevedo12 I found this app in Deepin forum and use it for now. This program allows you to automatically change to the scheme you are used to just by executing it from the terminal. Run this file with sudo permissions and choose theme what you want. Then 
`killall deepin-terminal`
 and start is back. If u doing right new theme was applying.

**Comment by z966768** [comment]
Soon

**Comment by smallyunet** [comment]
> [deepin-terminal-themes.zip](https://github.com/linuxdeepin/deepin-terminal/files/5542493/deepin-terminal-themes.zip)
> @dacevedo12 I found this app in Deepin forum and use it for now. This program allows you to automatically change to the scheme you are used to just by executing it from the terminal. Run this file with sudo permissions and choose theme what you want. Then
> `killall deepin-terminal`
> and start is back. If u doing right new theme was applying.

It doesn't work.

**Comment by shqear93** [comment]
The new terminal is really annoying! how to rollback to old version?

**Comment by happyd0ggie** [comment]
Deepin 20.1 released and added 10 themes for deepin-terminal. →
[https://www.deepin.org/en/2020/12/28/deepin-20-1-details-make-perfection/](url)

**Comment by yev-lab** [comment]
> > [deepin-terminal-themes.zip](https://github.com/linuxdeepin/deepin-terminal/files/5542493/deepin-terminal-themes.zip)
> > @dacevedo12 I found this app in Deepin forum and use it for now. This program allows you to automatically change to the scheme you are used to just by executing it from the terminal. Run this file with sudo permissions and choose theme what you want. Then
> > `killall deepin-terminal`
> > and start is back. If u doing right new theme was applying.
> 
> It doesn't work.

This program just redefine "DARK THEME" - not make new

**Comment by YutianGe** [comment]
More themes and custom themes have been updated in the latest release
