### ISSUE TITLE
终端使用alt+n(1-9)快捷键切换标签页

### ISSUE THREAD

**Issue by qcxiang** [linuxdeepin/deepin-terminal#31]
目前只能ctrl+tab键一个个切换，希望能支持alt+数字键(1-9)来快速切换到对应的标签页。
可参考KDE Konsole.

**Comment by chenzhiwei** [comment]
这个功能可以通过自己设置快捷键来实现，你仔细看一下 deepin-terminal 的设置就知道怎么做了。

**Comment by caozhendong** [comment]
> 这个功能可以通过自己设置快捷键来实现，你仔细看一下 deepin-terminal 的设置就知道怎么做了。

怎么配置，或者在哪里可以看到设置参考文档？deepin-terminal v1版本默认是Alt + 1~9来select window tab， 但是到了新版本默认变成了Ctrl + Shift + 1~9， 原因为何？是否可以保持Alt + 1~9的用户习惯

另， 期待答复“怎么配置，或者在哪里可以看到设置参考文档？”， 3q~

**Comment by chenzhiwei** [comment]
是这样的，深度终端的最新源码并没有公布出来，在最新版这个确实可以自己设置了。

另外，我认为深度公司既然决定重写的深度终端是老王那个版本的延续了，那么快捷键应该继承下去吧。

我一直使用习惯了 gnome-terminal ，除了这个切换标签外还有其他深度终端的快捷键行为让我无法适应，估计产品经理觉得他最懂怎么设计深度终端吧。

建议你尝试一下 Tilix ，也是个不错的终端。

**Comment by chenzhiwei** [comment]
对了，深度终端最开始也不是 `Alt + 数字` 来切换标签，但是它提供了自定义功能，用户可以改。

再后来老王就把 `Alt + 数字` 变成了默认值来切换标签，这是我五年前提的意见：https://bbs.deepin.org/post/29481?offset=1&postId=140201

这个 `Alt + 数字` 切换标签，`Alt + 0`切换到最后一个是很多软件的默认行为，比如 Chrome、Firefox 等等，我也实在很好奇深度为何不用这些众所周知的快捷键和行为。

**Comment by caozhendong** [comment]
> 是这样的，深度终端的最新源码并没有公布出来，在最新版这个确实可以自己设置了。
> 
> 另外，我认为深度公司既然决定重写的深度终端是老王那个版本的延续了，那么快捷键应该继承下去吧。
> 
> 我一直使用习惯了 gnome-terminal ，除了这个切换标签外还有其他深度终端的快捷键行为让我无法适应，估计产品经理觉得他最懂怎么设计深度终端吧。
> 
> 建议你尝试一下 Tilix ，也是个不错的终端。

感谢回复，

最新源码没有公布，你所讲的最新版是什么版本，你如何获取的？我当前版本为deepin-terminal 5.3.0.3
另， 通过该source code编译的可执行deepin-terminal同样无法得知更改“Ctrl+Shift+1-9”到“Alt + 1-9”的方法。

如你所述的最新版本可以配置，可否不吝赐教具体的配置方法？万分感谢！

其他终端我也有使用，现阶段除了该快捷键与我的使用习惯不符觉得别扭之外，其他的还可以接受，相比之下的终端直接打开文件夹等便捷操作还是很赞，利弊均衡，能解决这个问题我还是愿意切回来使用；

再次感谢你的建议和答复！

**Comment by chenzhiwei** [comment]
首先我和你一样只是深度的一个用户。

刚刚找到了：https://github.com/linuxdeepin/deepin-terminal/blob/5.4.0.11/src/assets/other/default-config.json#L203-L256

可以在这里下载 5.4: https://proposed-packages.deepin.com/dde-apricot/pool/main/d/deepin-terminal/

**Comment by caozhendong** [comment]
> 首先我和你一样只是深度的一个用户。
> 
> 刚刚找到了：https://github.com/linuxdeepin/deepin-terminal/blob/5.4.0.11/src/assets/other/default-config.json#L203-L256
> 
> 可以在这里下载 5.4: https://proposed-packages.deepin.com/dde-apricot/pool/main/d/deepin-terminal/

Got it, 谢谢，这对我帮助很大。

**Comment by qcxiang** [comment]
最新的社区版20.1，深度终端版本5.4.0.6，实测验证已支持设置切换标签页快捷键。
