### ISSUE TITLE
终端远程管理功能支持多级中间主机自动登陆跳转

### ISSUE THREAD

**Issue by qcxiang** [linuxdeepin/deepin-terminal#32]
实际使用场景：
登陆目标机器需要通过堡垒机之类，希望终端远程管理能支持配置自动登陆跳转，类似SecureCRT中的login script,录制一段脚本，登陆的时候自动执行就能登陆到目标机器。

**Comment by YutianGe** [comment]
Thank you for your suggestion. We will consider it carefully
