### ISSUE TITLE
[BUG] Text issues in the terminal view

### ISSUE THREAD

**Issue by N1coc4colA** [linuxdeepin/deepin-terminal#33]
How to produce the bug
Maximize the window, switch to fullscreen, then:
$ clear
Then leave the fullscreen, the text is hidden by the titlebar. You can't see what you're typing :/ Maybe you should make the plain text edit or the thing that shows the text in a layout or kinda like to fix this UI bug...

**Comment by YutianGe** [comment]
Unable to reproduce, you can try to update the latest version to try
