### ISSUE TITLE
[BUG] Default light theme is not compatible with Vim's default color scheme

### ISSUE THREAD

**Issue by xjtu-blacksmith** [linuxdeepin/deepin-terminal#35]
The default light theme seems to work badly with Vim's default color scheme ...

In dark theme, some of the contents were in white color:

![图片](https://user-images.githubusercontent.com/42454373/94152411-1945f080-feae-11ea-8fe5-e107abe3363d.png)

while they were still white in light theme and then *disappeared* ...

![图片](https://user-images.githubusercontent.com/42454373/94152430-206cfe80-feae-11ea-8758-e6ade516cc90.png)

**Comment by YutianGe** [comment]
The theme section has been optimized, you can try to update the latest version
