### ISSUE TITLE
QTermWidget used as a default title for a new tab

### ISSUE THREAD

**Issue by nanoant** [linuxdeepin/deepin-terminal#36]
I have `zsh` with clean vanilla `.zshrc` and when I don't setup explicit `precmd()` to change terminal title I get *"QTermWidget"* my new tab title. I think Deepin Terminal could default to some better title, e.g. `/bin/shell #1` where (`shell` is my shell name).

![image](https://user-images.githubusercontent.com/103067/94347850-170f9d80-0038-11eb-8c53-09f2539c74e9.png)

**Comment by lidanger** [comment]
True. A little awkward.

![截图录屏_选择区域_20200929180740](https://user-images.githubusercontent.com/4464921/94545305-eff6dd00-027e-11eb-8527-548664dcd4c1.png)

**Comment by z966768** [comment]
please try the newest version
