### ISSUE TITLE
Window title bar is way too big

### ISSUE THREAD

**Issue by hhaim** [linuxdeepin/deepin-terminal#37]
![image](https://user-images.githubusercontent.com/13034429/94600700-f430f380-029a-11eb-9989-4e91fa7e647e.png)

The size of the header should be the same as one line, 
Is there a way to change it?

**Comment by nepali-prabhat** [comment]
I want to change the size of the header too. I don't like the new update

**Comment by YutianGe** [comment]
We'll consider it. Thank you for your feedback
