### ISSUE TITLE
Window effect + terminal does not work together 

### ISSUE THREAD

**Issue by hhaim** [linuxdeepin/deepin-terminal#38]
![image](https://user-images.githubusercontent.com/13034429/94600831-2e9a9080-029b-11eb-9d8b-34baaf6c6b41.png)

**Comment by z966768** [comment]
please try the newest version

**Comment by hhaim** [comment]
@z966768 ack, this was solved and I like the new improvement, 
In general the new version 20.1 is a very good improvement, but still has some bugs, will report them separately
