### ISSUE TITLE
[BUG :fire: ] Manjaro 源中版本显示异常

### ISSUE THREAD

**Issue by Thoxvi** [linuxdeepin/deepin-terminal#44]
软件版本: `deepin-terminal-5.2.37-1`
系统版本: `Linux 5.8.16-2-MANJARO #1 SMP PREEMPT Mon Oct 19 11:33:03 UTC 2020 x86_64 GNU/Linux`

<img width="500" alt="截屏工具_deepin-terminal_20201106101541" src="https://user-images.githubusercontent.com/12222073/98318313-5824a580-2019-11eb-8724-5ac83295d5bc.png">

这个问题已经持续几个月了

**Comment by felixonmars** [comment]
目前所有 DDE v20 应用均只支持在 DDE 桌面环境使用。在 KDE 等其他桌面环境使用出现这种现象是已知问题，暂不支持。

请考虑切换到 DDE 桌面环境或使用 deepin-terminal-old。

**Comment by Thoxvi** [comment]
了解了，那么这个 Issue 需要关闭吗？

**Comment by Thoxvi** [comment]
补充一下，根据我个人体验，建议安装 `deepin-terminal-old`
