### ISSUE TITLE
deepin-terminal的bug，无法在codeblocks中使用deepin-terminal

### ISSUE THREAD

**Issue by w190322** [linuxdeepin/deepin-terminal#45]
deepin20，codeblocks环境设置里试图把控制台使用终端由默认的xterm改为deepin-terminal但是失败，原来15版本的时候是可以的

**Comment by YutianGe** [comment]
感谢您的反馈，我们会优化此问题！

**Comment by w190322** [comment]
不用麻烦了，这个问题已经解决了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月17日(周一) 晚上9:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [linuxdeepin/deepin-terminal] deepin-terminal的bug，无法在codeblocks中使用deepin-terminal (#45)




 
感谢您的反馈，我们会优化此问题！

**Comment by YutianGe** [comment]
使用最新版本已经没有此问题了，是吗？

**Comment by w190322** [comment]
不是版本问题，编辑器配置里面有一项是配置终端的，默认xterm。我当时是不知道那一项命令怎么写才能正确配置为使用deepin终端，后来论坛有人帮解决了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月17日(周一) 晚上9:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [linuxdeepin/deepin-terminal] deepin-terminal的bug，无法在codeblocks中使用deepin-terminal (#45)




 
使用最新版本已经没有此问题了，是吗？

**Comment by YutianGe** [comment]
好的，感谢您的反馈！
