### ISSUE TITLE
新建窗口通过ALT+数字，跳转到对应窗口

### ISSUE THREAD

**Issue by okshall** [linuxdeepin/deepin-terminal#46]
能实现像ubuntu自带terminal 那样，通过ATL+ 编号 切换对应的窗口吗

**Comment by chenzhiwei** [comment]
~~这个功能可以通过自己设置快捷键来实现，你仔细看一下 deepin-terminal 的设置就知道怎么做了。~~

最新版（>= 5.4）的深度终端可以设置了，估计元旦前应该能发布。
