### ISSUE TITLE
symbol lookup error:undefined symbol

### ISSUE THREAD

**Issue by vela-security** [linuxdeepin/deepin-terminal#47]
./deepin-terminal: symbol lookup error: ./deepin-terminal: undefined symbol: _ZN11QTermWidget14sig_matchFoundEv

**Comment by felixonmars** [comment]
Cannot reproduce on Arch. What OS are you using?

**Comment by vela-security** [comment]
> 无法在Arch上复制。您正在使用什么操作系统？

deepin  5.4.70-amd64-desktop #1 SMP Wed Oct 14 15:24:23 CST 2020 x86_64 GNU/Linux

**Comment by z966768** [comment]
尝试更新一下dtk环境
