### ISSUE TITLE
能否保持Alt+1~9作为select window的默认快捷键，或如何通过新的config规则改变现有Ctrl+Shift+1~9的行为？

### ISSUE THREAD

**Issue by caozhendong** [linuxdeepin/deepin-terminal#49]
目前只能通过快捷键Ctrl+Shift+1-9进行跳转，然而大多数用户的操作习惯是Alt+1-9,；

我想要更改这一行为，follow已经习惯的快捷键习惯该怎么配置，或者在哪里可以看到设置参考文档？

deepin-terminal v1版本默认是Alt + 1-9来select window tab， 但是到了新版本默认变成了Ctrl + Shift + 1-9， 原因为何？default行为是否可以保持Alt + 1-9的大众用户习惯？

另， 期待答复“怎么配置，或者在哪里可以看到设置参考文档？”， 3q~

**Comment by caozhendong** [comment]
This issue has been fixed after upgraded deepin-terminal version 5.4.0.6;

The deb installation package can be obtained through the following link. 
And thanks Chen Zhiwei's help on this issue:
https://github.com/linuxdeepin/deepin-terminal/issues/31#issuecomment-751201090

**Comment by amengGT** [comment]
终端5.4.0.6上您可以在自由设置标签跳转快捷键。设置选项在终端设置框->快捷键->标签页一栏中。
感谢您的反馈！
