### ISSUE TITLE
Deepin-Terminal 5.4.0.6 theme should be reflush after slipt window 

### ISSUE THREAD

**Issue by caozhendong** [linuxdeepin/deepin-terminal#50]
1. Update deepin-terminal version 5.4.0.6
2. Change the theme such as Elementary
3. Find the theme is change well
4. Slipt window
5. the new slipt window theme is diffrent with Elementary --> issue
![deepin-terminal_5 4 0 6_theme_issue](https://user-images.githubusercontent.com/45852832/103196662-88a10580-491f-11eb-96bd-2324998de21b.png)

**Comment by amengGT** [comment]
1. We tested on 5.4.0.6 is not found on the problem you said
2. During the development process we have found and solved this problem
3. The link you provided cannot be opened, you can send us an email to inform us of the details of the problem. My email address is zhangmeng@uniontech.com 

Thanks!

**Comment by caozhendong** [comment]
> 1. We tested on 5.4.0.6 is not found on the problem you said
> 2. During the development process we have found and solved this problem
> 3. The link you provided cannot be opened, you can send us an email to inform us of the details of the problem. My email address is [zhangmeng@uniontech.com](mailto:zhangmeng@uniontech.com)
> 
> Thanks!

I have sent a feedback email to you about this issue. I don’t know if you received it. 
Regarding the second point you mentioned: During the development process we have found and solved this problem.
I tried to remove my local terminal and re-apt install it, but the issue still exists, can you reproduce? 
any comments?

Looking forward to your feedback, Thanks!

**Comment by caozhendong** [comment]
Update: 

The issue only occurs when using shortcut keys (such as `Ctrl+Shift+J`, and my behavior `Ctrl+Shift+E` for the same action "纵向分屏") to split the screen, instead of using the mouse.

**Comment by happyd0ggie** [comment]
> Update:
> 
> The issue only occurs when using shortcut keys (such as `Ctrl+Shift+J`, and my behavior `Ctrl+Shift+E` for the same action "纵向分屏") to split the screen, instead of using the mouse.

Same issue, see post: [https://bbs.deepin.org/post/209093](url)

**Comment by ch593030323** [comment]
U can update the newest master code, the bug already is fixed.

**Comment by caozhendong** [comment]
This issue has been fixed on deepin-terminal-5.4.23
