### ISSUE TITLE
Middle click on the tap doesn't work

### ISSUE THREAD

**Issue by shqear93** [linuxdeepin/deepin-terminal#53]
I used to use middle click to terminate the terminal tap, now with Deepin 20 it doesn't work!
also Ctrl + W and Ctrl + Shift + W doesn't work!

I use deepin terminal v5.4.0.6

Any idea ??

**Comment by macosunity** [comment]
you can use Alt+W to close tab,  "middle click to terminate" function will be added later

**Comment by shqear93** [comment]
@macosunity `Alt + W` is not working

**Comment by YutianGe** [comment]
There are Settings for keyboard shortcuts
