### ISSUE TITLE
Add an option to stick terminal to top

### ISSUE THREAD

**Issue by qodroi** [linuxdeepin/deepin-terminal#54]
I wonder why it is not possible to stick the window to the top? I really need it in my work environment.

**Comment by macosunity** [comment]
If you use Alt + F2 shortcut key, you will get a "stick the window to the top" terminal which we called "quake terminal"

**Comment by qodroi** [comment]
> If you use Alt + F2 shortcut key, you will get a "stick the window to the top" terminal which we called "quake terminal"

Alt + F2 opens an input box for me to run a command in Ubuntu Gnome

**Comment by YutianGe** [comment]
There are relevant keyboard Settings in the Settings
