### ISSUE TITLE
[Arch + KDE] Weird graphical artifacts

### ISSUE THREAD

**Issue by Graeme22** [linuxdeepin/deepin-terminal#58]
Hello, on my Arch the application has a weird visual bug. I installed from the `deepin-terminal` [community package](https://archlinux.org/packages/?name=deepin-terminal).

![glitch](https://user-images.githubusercontent.com/4185684/106396957-e9f54200-63bf-11eb-9b1b-452694648f88.png)

**Comment by felixonmars** [comment]
It's a known bug on KDE.

**Comment by Graeme22** [comment]
Interesting. I do have the application on another KDE machine (Kubuntu) and haven't had any issues.

**Comment by justforlxz** [comment]
Kubuntu may be running the gtk version of deepin-terminal, and arch is running the qt version of deepin-terminal. We are removing the restriction because the qt theme plugins we provide may affect other qt programs. If everything is in order, it will be in the near future Release the update.

**Comment by Graeme22** [comment]
Makes sense. I'll be watching for the update!
