### ISSUE TITLE
BUG - Empty dropdown menu after rightclick on scrollbar

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/deepin-terminal#59]
https://user-images.githubusercontent.com/39202451/107058258-abeb8a00-67d4-11eb-8646-8a0d3a83e5c0.mp4

**Comment by wangliang-terminal** [comment]
This problem does exist, we will fix this bug later, thank you very much for your feedback！

**Comment by raspin0** [comment]
Fixed in 20.2 thanks
