### ISSUE TITLE
Cannot install on debian based distro

### ISSUE THREAD

**Issue by maxjf1** [linuxdeepin/deepin-terminal#60]
Currently, it isn't possible to complete the installation process in debian based distro (Ubuntu)

Commands followed:
```bash
sudo apt build-dep .
mkdir build && cd build
cmake ..
```
Output:
```bash
-- Checking for one of the modules 'dtkgui'
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:741 (message):
  None of the required 'dtkgui' found
Call Stack (most recent call first):
  CMakeLists.txt:57 (pkg_search_module)


-- Keyboard layouts will be installed in: /usr/share/terminalwidget5/kb-layouts
-- Color schemes will be installed in: /usr/share/terminalwidget5/color-schemes
-- Translations will be installed in: /usr/share/terminalwidget5/translations
dtk-settings-tools could not be found at /dtk-settings
-- Configuring incomplete, errors occurred!
See also "/home/maxjf1/projetos/deepin-terminal/build/CMakeFiles/CMakeOutput.log".
```

Also tried to install `dtkgui` and `libdtkgui-dev` via apt, but they cannot be found.

It's possible to provide the binary when a release is created?

System info:
```bash
                          ./+o+-       maxjf1@maxjf1-G3-3579
                  yyyyy- -yyyyyy+      OS: Ubuntu 20.10 groovy
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.8.0-41-generic
           .++ .:/++++++/-.+sss/`      Uptime: 3h 46m
         .:++o:  /++++++++/:--:/-      Packages: 2311
        o:+o+:++.`..```.-/oo+++++/     Shell: zsh 5.8
       .:+o:+o/.          `+sssoo+/    Resolution: 1920x1080
  .++/+:+oo+o:`             /sssooo.   DE: GNOME 3.38.3
 /+++//+:`oo+o               /::--:.   WM: Mutter
 \+/+o+++`o++o               ++////.   WM Theme: Adwaita
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Yaru-dark [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: McMojave-circle-dark
        \+.++o+o``-````.:ohdhhhhh+     Font: Garuda 11
         `:o+++ `ohhhhhhhhyo++os:      Disk: 56G / 69G (86%)
           .o:`.syhhhhhhh/.oo++o`      CPU: Intel Core i5-8300H @ 8x 4GHz [50.0°C]
               /osyyyyyyo++ooo+++/     GPU: GeForce GTX 1050
                   ````` +oo+++o\:     RAM: 7741MiB / 15854MiB
                          `oo++.      
```

**Comment by juteman** [comment]
As far as I know, dde is available on ubuntu. I think u can get more help by https://github.com/UbuntuDDE

**Comment by ClayStan** [comment]
You need install dtkgui : https://github.com/linuxdeepin/dtkgui
Debian unstable and bulleye repo has this package : https://packages.debian.org/search?keywords=dtkgui&searchon=sourcenames&suite=all&section=all

**Comment by ClayStan** [comment]
Strictly speaking, Ubuntu cannot be said to be based on Debian. If you want to use Deepin software or DDE on Ubuntu, it is recommended to try UbuntuDDE : https://ubuntudde.com/

**Comment by maxjf1** [comment]
In my case, i just want to build the terminal app to it's latest version. [The latest version in Snap store](https://snapcraft.io/deepin-terminal) is old. is there a way to compile it using ubuntu? (or maybe using some docker image)

> You need install dtkgui : https://github.com/linuxdeepin/dtkgui

@ClayStan  how can i install it? the GitHub repo doesn't have any instructions. Do you think by installing it, i will be able to compile using ubuntu?

**Comment by juteman** [comment]
> In my case, i just want to build the terminal app to it's latest version. [The latest version in Snap store](https://snapcraft.io/deepin-terminal) is old. is there a way to compile it using ubuntu? (or maybe using some docker image)
> 
> > You need install dtkgui : https://github.com/linuxdeepin/dtkgui
> 
> @ClayStan how can i install it? the GitHub repo doesn't have any instructions. Do you think by installing it, i will be able to compile using ubuntu?

Happy Chinese New Year！ 
dtkgui is not port to cmake now, u can use qmake to generator makefile, then build with make. It can compile on ubuntu I think.

**Comment by maxjf1** [comment]
> Happy Chinese New Year！
> dtkgui is not port to cmake now, u can use qmake to generator makefile, then build with make. It can compile on ubuntu I think.

Happy chinese new year :smile: 

I will try to research about it. I don't know much about cmake or compiling in linux, i'm an average linux user, just looking to update the deepin terminal i have (it's the best terminal i've found so far)

**Comment by juteman** [comment]
> > Happy Chinese New Year！
> > dtkgui is not port to cmake now, u can use qmake to generator makefile, then build with make. It can compile on ubuntu I think.
> 
> Happy chinese new year 😄
> 
> I will try to research about it. I don't know much about cmake or compiling in linux, i'm an average linux user, just looking to update the deepin terminal i have (it's the best terminal i've found so far)

After Chinese New Year holiday (2.18)， I will ask the dtk developers to complete the documentation.

**Comment by XMuli** [comment]
@maxjf1 dtkgui is already ready for Ubuntu through PPA: One needs to add this PPA:

[https://launchpad.net/~ubuntudde-dev/+archive/ubuntu/stable](https://launchpad.net/~ubuntudde-dev/+archive/ubuntu/stable)

If you need more help， them may be able to help you.   see [support](https://ubuntudde.com/support/)

**Comment by maxjf1** [comment]
@xmuli please check my initial comment. Um not in dtkui. Um using Ubuntu 20 with gnome and want to use the latest terminal

Currently, i'm using an older version available in snap store

**Comment by XMuli** [comment]
[deepin-terminal](https://github.com/linuxdeepin/deepin-terminal ) is based on DTK development (dtkgui is one of the core parts of DTK).  

If you want to install deepin-terminal based on dtk in ubuntu, then you must install dtkgui, dtkcore, dtkwidget and the corresponding dtkgui-dev, dtkcore-dev, dtkwidget-dev; in order to be able to compile successfully (software starting with names like deepin-xxx, dde-xxx); usually this is the case

[deepin-terminal-gtk](https://github.com/linuxdeepin/deepin-terminal-gtk) is an older version of the terminal, based on gtk, which is no longer maintained

**Comment by ClayStan** [comment]
> In my case, i just want to build the terminal app to it's latest version. [The latest version in Snap store](https://snapcraft.io/deepin-terminal) is old. is there a way to compile it using ubuntu? (or maybe using some docker image)
Yeah, you can compile it using ubuntu, you just need install the build-dep packages, and use  debuild or other tools to build the deb format package. 
If you want to compile snap format package,  you should use other ways: https://ubuntu.com/tutorials/create-your-first-snap#1-overview
> 
> > You need install dtkgui : https://github.com/linuxdeepin/dtkgui
> 
> @ClayStan how can i install it? the GitHub repo doesn't have any instructions. Do you think by installing it, i will be able to compile using ubuntu?
same way, the source code include the debian directory, you just need install build-dep packages and run debuild or other tools to build the deb packages.
You know how to build deb packages, right?
If you don't know how to build the deb package, you can see the documents of debian:
https://www.debian.org/doc/manuals/maint-guide/
https://www.debian.org/doc/manuals/debmake-doc/
https://www.debian.org/doc/debian-policy/

**Comment by maxjf1** [comment]
would be great to have an docker image for compiling this.
