### ISSUE TITLE
BUG - Receive some extra text after moving vertical splitter to left or right bound

### ISSUE THREAD

**Issue by jtstrs** [linuxdeepin/deepin-terminal#64]
https://user-images.githubusercontent.com/17281731/110113655-77172680-7dc4-11eb-89d0-7a7dfe541e55.mp4

**Comment by jtstrs** [comment]
Ubuntu 20.04.2 LTS

**Comment by wangliang-terminal** [comment]
This version of deepin-terminal on Ubuntu 20.04.2 has not been maintained for a long time，you can use deepin 20 os and try to build and install new version of deepin-terminal using the latest dev branch code(which is developed with Qt and DTK), the latest version of deepin-terminal has optimized for this issue.

**Comment by wangliang-terminal** [comment]
You can also try to build and run the newest deepin-terminal on ubuntudde version: [https://ubuntudde.com/](url)
