### ISSUE TITLE
终端执行程序后闪退问题

### ISSUE THREAD

**Issue by WwwwwyDev** [linuxdeepin/deepin-terminal#66]
当执行`deepin-terminal --keep-open -e ls`或者`deepin-terminal--keep-open -e python 1.py`跳出的终端仍然立刻闪退，请问`--keep-open`这个命令有什么作用，有没有类似于konsole的`--hold`命令，在执行完程序后可以不立刻退出。

**Comment by wwyd123456** [comment]
> 当执行`deepin-terminal --keep-open -e ls`或者deepin-terminal --keep-open -e python 1.py`跳出的终端仍然立刻闪退，请问`--keep-open`这个命令有什么作用，有没有类似于konsole的`--hold`命令，在执行完程序后可以不立刻退出。
