### ISSUE TITLE
[QUESTION] Click on URLs?

### ISSUE THREAD

**Issue by tomasnorre** [linuxdeepin/deepin-terminal#68]
Hi, 

Does an option, setting or plugin exist so that I can press ctrl and mouse-click to open URLs in default browser? had that for iTerm when I was on MacOS. Miss that feature, but haven't found a linux Terminal that I like better than deepin.

**Comment by ch593030323** [comment]
The terminal with the default setting is able to open the url(eg: www.google.com) by pressing ctrl and mouse-click. I have no idea how you do it. please tell me the detail steps?

**Comment by tomasnorre** [comment]
I read that yesterday too, but for me it's not working. 

Info: 
Ubuntu Budgie 20.4

```
 ➜ deepin-terminal --version
Deepin Terminal 
Copyright 2011-2017 Deepin, Inc.
```

Doesn't say version number for deepin, but surprised that it isn't more up to date. My apt does say that updates exists. 
Perhaps I should start there. 

Steps to reproduce in my setup: 

1. 
```
curl -I https://www.google.com                   
HTTP/2 200 
content-type: text/html; charset=ISO-8859-1
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
date: Fri, 19 Mar 2021 05:26:58 GMT
...
```

2. Press ctrl + left mouse (no action, no underline, no nothing) 
3. Press ctrl + right mouse (no action, no underline, no nothing)

**Comment by ch593030323** [comment]
Our latest version does not yet support Ubuntu Budgie 20.4. You are using a very old version that is no longer maintained.

**Comment by tomasnorre** [comment]
I don't know how old it is, and how many releases made since, but from copyright notice its old `Copyright 2011-2017 Deepin, Inc.`

```
Package: deepin-terminal
Version: 5.0.0+ds1-1
```

I have it installed with `apt install deepin-terminal`
APT-Sources: http://de.archive.ubuntu.com/ubuntu focal/universe amd64 Packages

With this laptop I have never been on older Ubuntu Budgies, so it's not a left over from an upgrade.

**Comment by tomasnorre** [comment]
I'm closing this as it isn't a generic problem but my problem.
