### ISSUE TITLE
Allowing multiple shortcut to run same command

### ISSUE THREAD

**Issue by ardiya** [linuxdeepin/deepin-terminal#69]
Currently a key can only have 1 shortcut, for example ["previous_workspace" can only have Ctrl+Tab shortcut, source code here](https://github.com/linuxdeepin/deepin-terminal/blob/4068a27936efd814a97e423f06756abd081b697c/src/assets/other/default-config.json#L120-L123)

Could you please support multiple shortcut for to run same command? 

I believe there are many user who will have same issue. For example, Ctrl+PageUp and Ctrl+Shift+Tab is pretty common shortcut to go to previous tab/workspace, see the list below. I believe it will be up to user to have alternative and not stuck with just one shortcut.
- [Microsoft Excel 2019, Ctrl + Page Up: Move to the previous sheet in a workbook](https://defkey.com/what-means/ctrl-pageup#popularshortcut-7552)
- [Google Chrome, Ctrl + Page Up: Jump to the previous open tab](https://defkey.com/what-means/ctrl-pageup#shortcut-3185)
- [Firefox, Ctrl + Page Up: Previous tab](https://defkey.com/what-means/ctrl-pageup#shortcut-61)
- [Sublime Text, Ctrl + Page Up: Cycle up through tabs](https://defkey.com/what-means/ctrl-pageup#shortcut-11335)

**Comment by ch593030323** [comment]
We will follow up on this issue, thank you for your feedback
