### ISSUE TITLE
[Feat] New quake mode window animation

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/deepin-terminal#7]
Press `Alt`+`F2` to open quake window (shown).

![Screen Capture_select-area_20200621173138](https://user-images.githubusercontent.com/65664227/85221488-bfcdb180-b3e6-11ea-8426-23c90339c0c4.png)

**Actual:**
Window animation transitions from center.

**Desired:**
Window animation transitions from top.

uname -r
5.7.4-arch1-1

**Comment by z966768** [comment]
you mean you want to add a drop-down animation effect?

**Comment by balibebas** [comment]
yes

**Comment by balibebas** [comment]
Yes, that's what I mean. A drop-down effect as opposed to opening the quake window from the center using scale/fade. I realize the team has bigger ticket items right now and I'm personally not happy with the new look of the terminal so please feel free to close as I may be switching to Hyper or something black and green.

**Comment by ghost** [comment]
Yes, that's what I mean. A drop-down effect as opposed to opening the quake window from the center using scale/fade.

**Comment by ghost** [comment]
Looks like this change was made in a recent update. Sweet.

![Peek 2020-07-30 23-05](https://user-images.githubusercontent.com/65664227/88939523-38167500-d2b9-11ea-99e2-9e8528b04062.gif)
