### ISSUE TITLE
No Undo Functionality is present

### ISSUE THREAD

**Issue by AcidRain9** [linuxdeepin/deepin-terminal#70]
There's no undo functionality, almost all the other terminals I used have this feature.
Example. If I type something and press Ctrl+Z nothing will happen

The gnome-terminal implements it very gracefully some notes should be taken from it

**Comment by ardiya** [comment]
I'm not part of deepin team, but Ctrl+Z isn't undo in most terminal.

Ctrl+Z is for suspending process(by sending SIGTSTP signal). Ctrl+C on the other hand is killing the process(by sending SIGINT signal). [see more details here](https://askubuntu.com/a/510816/1026214)

**Comment by AcidRain9** [comment]
> I'm not part of deepin team, but Ctrl+Z isn't undo in most terminal.
> 
> Ctrl+Z is for suspending process(by sending SIGTSTP signal). Ctrl+C on the other hand is killing the process(by sending SIGINT signal). [see more details here](https://askubuntu.com/a/510816/1026214)

Yeah you are right, I just checked again and it appears that the distro I'm using have some sort of custom Terminal that has that functionality I tried it on vanilla Ubuntu and indeed there's no undo.
