### ISSUE TITLE
Can't change my shell after install deepin-desktop

### ISSUE THREAD

**Issue by JGGoncalves** [linuxdeepin/deepin-terminal#72]
Hello, I'm using Fedora 34 Beta and Decided to install the deepin-desktop package group, after logging into Deepin, 
I noticed that my shell has changed to bash (I use fish as my default shell).

At the moment I can not change nor using chsh (both user and sudo), my /usr/bin/passwd is set up correctly (my user keeps using fish as the default shell).
My solution attempt was to enter the gnome-terminal, bash keeps running by default and does not change.
Also when I try to change in chsh `sudo chsh -s /usr/bin/fish` this returns `chsh: Shell not changed.`

Don't know exactly what to do at the moment and would like help.
Thanks.

**Comment by YutianGe** [comment]
Thank you for your feedback. We have also noticed this scenario

**Comment by ch593030323** [comment]
I think it is due to the system. Before working in Redhat, i also cannot chsh $$SHELL.
In websit "https://bugzilla.redhat.com/show_bug.cgi?id=1063552" can see some bug issue.
U can try that other terminals like gnome and konsole also have the same problem.

**Comment by Sky-Asher** [comment]
This problem has not been reported for more than 1 month and will be closed soon. Thank you for your support!
