### ISSUE TITLE
Crash on Ubuntu 21

### ISSUE THREAD

**Issue by pulberg** [linuxdeepin/deepin-terminal#74]
Removed and re-installed with same errors - 

deepin-terminal[3037]: segfault at 968 ip 00007f17a30c5314 sp 00007fffea16caf0 error 4 in libX11.so.6.4.0[7f17a30b4000+8c000]
../../../../../gdk/x11/gdkwindow-x11.c:5650 drawable is not a native X11 window
invalid cast from 'GdkWaylandWindow' to 'GdkX11Window'
gdk_x11_display_get_xdisplay: assertion 'GDK_IS_DISPLAY (display)' failed
void vte_terminal_match_set_cursor_type(VteTerminal*, int, GdkCursorType): assertion 'tag >= 0' failed
libwnck is designed to work in X11 only, no valid display found

**Comment by felixonmars** [comment]
I don't think you are using this repo. The legacy version located at https://github.com/linuxdeepin/deepin-terminal-gtk uses libwnck and gdk stuff.

**Comment by pulberg** [comment]
Thanks for clarification, i am trying this repo and getting errors during make like - 

/opt/deepin-terminal-5.4.0.20/3rdparty/terminalwidget/lib/Filter.cpp:234:47: error: ‘QString::QString(const char*)’ is private within this context
  234 |                 strCommand = QString("sudo %1").arg(strCommand);

Should I make a new issue for this?

**Comment by felixonmars** [comment]
Yes, please create a new issue for that.
