### ISSUE TITLE
deepin终端配色反人类

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/deepin-terminal#75]
deepin在~/.bashrc里面写的：
#Set LS_COLORS environment by Deepin
#if [[ ("$TERM" = *256color || "$TERM" = screen* || "$TERM" = xterm* ) && -f /etc/lscolor-256color ]]; then
#eval $(dircolors -b /etc/lscolor-256color)
#else
#eval $(dircolors)
#fi
这一段，导致所有终端浅色配色变得非常难看，可以说是反人类，让我不爽很久
linux一个比windows好的地方就是终端，这样一配色，终端就给废了

![image](https://user-images.githubusercontent.com/12093211/115489610-09995980-a28f-11eb-88e3-62618350d3df.png)

看看上面那黄色的文件名，谁能看出来文件名是啥？

 希望deepin把这段从bashrc里面移除

**Comment by Kyvrel** [comment]
+1 配色太丑了
选深色主题, 蓝色根本看不清

**Comment by chenzhiwei** [comment]
代码注释配色反人类，可以用如下方法解决：

找到`/usr/share/terminalwidget5/color-schemes/*.colorschme`中第57行中的`24, 24, 178`，修改成`46, 100, 166`。

@justforlxz

**Comment by eddiecailinux** [comment]
+1 配色太丑了。为什么不默认搞个好看的配色。我们还得自己改

**Comment by ch593030323** [comment]
文件类型的色值读取的是/etc/lscolor-256color的，可以试试修改这个文件

**Comment by Sky-Asher** [comment]
此问题已超过1个月无人响应，即将关闭，感谢您的支持！
