### ISSUE TITLE
Search feature not working

### ISSUE THREAD

**Issue by carlos-contreras** [linuxdeepin/deepin-terminal#76]
This is my deepin terminal, the Linux distro is popOS, no mater what I do I can't make the search feature work, it appear it can't find anything

![image](https://user-images.githubusercontent.com/10210552/119403528-bf473600-bc9b-11eb-895f-e576411aa784.png)

Here is a demonstration of the issue

![Peek 2021-05-24 14-25](https://user-images.githubusercontent.com/10210552/119403675-f4538880-bc9b-11eb-8162-cf7efeae9c5c.gif)

**Comment by carlos-contreras** [comment]
I hit the enter key after typing the search terms, what I'm missing here?

**Comment by YutianGe** [comment]
You're using the master branch code that compiles itself, right? You can try opening it using the dev branch

**Comment by ch593030323** [comment]
it looks like  deepin-terminal-gtk. u can try deepin-terminal that Search-feature is working finely.

**Comment by Sky-Asher** [comment]
This problem has not been reported for more than 1 month and will be closed soon. Thank you for your support!
