### ISSUE TITLE
[deepin 20.1] Terminal theme with problems

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/deepin-terminal#77]
By setting the Terminal theme as "Default"; to adjust to the system theme (I use the automatic theme); upon restart, the Terminal starts with the pre-defined Dark theme.

This cycle occurs every time the system is restarted.

<br>

![Captura de Tela_deepin-terminal_20201229084932](https://user-images.githubusercontent.com/45263160/103371019-2bd35580-4aad-11eb-8dfc-0324e5e395d0.png)

<br>

deepin 20.1 (1010) / OsBuild=11031.108

**Comment by Sky-Asher** [comment]
It may be caused by the other party's forced shutdown and other operations.
This problem has been unanswered for more than a month and will be closed soon.Thank you for your support!
