### ISSUE TITLE
[Feat] Classic mode

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/deepin-terminal#8]
Add classic mode so users who upgraded can go back to the old window style:

![Screen Capture_deepin-terminal_20200529054335](https://user-images.githubusercontent.com/65664227/85221579-497d7f00-b3e7-11ea-8f57-19b8ca3f5e1c.png)

**Comment by z966768** [comment]
Please try the latest version

**Comment by z966768** [comment]
Please try the latest version

**Comment by amit-gshe** [comment]
I'll keep the 5.0.x version for that the latest version was ugly and not easy to use IMO. 

1. The tab get so large and not support to mv or resort.
2. I can't customize the Text color or background color.
3. Unable to choose tab via shortcut `alt+number`.

**Comment by amit-gshe** [comment]
> Add classic mode so users who upgraded can go back to the old window style:
> 
> ![Screen Capture_deepin-terminal_20200529054335](https://user-images.githubusercontent.com/65664227/85221579-497d7f00-b3e7-11ea-8f57-19b8ca3f5e1c.png)

For Arch users can downgrade the package to `5.0.4.1-1`
```
amit@Arch ~ % downgrade deepin-terminal
可选的包：

-   1)  deepin-terminal    3.2             1  x86_64  (远端)
-   2)  deepin-terminal    3.2.1           1  x86_64  (远端)
-   3)  deepin-terminal    3.2.1.1         1  x86_64  (远端)
-   4)  deepin-terminal    3.2.1.1         2  x86_64  (远端)
-   5)  deepin-terminal    3.2.1.2         1  x86_64  (远端)
-   6)  deepin-terminal    3.2.2           1  x86_64  (远端)
-   7)  deepin-terminal    3.2.2.1         1  x86_64  (远端)
-   8)  deepin-terminal    3.2.3           1  x86_64  (远端)
-   9)  deepin-terminal    3.2.3.1         1  x86_64  (远端)
-  10)  deepin-terminal    3.2.4           1  x86_64  (远端)
-  11)  deepin-terminal    3.2.5           1  x86_64  (远端)
-  12)  deepin-terminal    3.2.5.1         1  x86_64  (远端)
-  13)  deepin-terminal    3.2.6           1  x86_64  (远端)
-  14)  deepin-terminal    3.2.7           1  x86_64  (远端)
-  15)  deepin-terminal    3.2.7.1         1  x86_64  (远端)
-  16)  deepin-terminal    5.0.0           1  x86_64  (远端)
-  17)  deepin-terminal    5.0.4.1         1  x86_64  (远端)
   18)  deepin-terminal    5.2.1           1  x86_64  (远端)
   19)  deepin-terminal    5.2.1           2  x86_64  (远端)
-  20)  deepin-terminal    5.2.2.20200601  1  x86_64  (远端)
-  21)  deepin-terminal    5.2.2.20200601  1  x86_64  (本地)
   22)  deepin-terminal    5.2.4           1  x86_64  (远端)
   23)  deepin-terminal    5.2.5           1  x86_64  (远端)
   24)  deepin-terminal    5.2.6           1  x86_64  (远端)
   25)  deepin-terminal    5.2.7           1  x86_64  (远端)
   26)  deepin-terminal    5.2.8           1  x86_64  (远端)
   27)  deepin-terminal    5.2.9           1  x86_64  (远端)
   28)  deepin-terminal    5.2.10          1  x86_64  (远端)
   29)  deepin-terminal    5.2.11          1  x86_64  (远端)
   30)  deepin-terminal    5.2.12          1  x86_64  (远端)
   31)  deepin-terminal    5.2.13          1  x86_64  (远端)
   32)  deepin-terminal    5.2.14          1  x86_64  (远端)
   33)  deepin-terminal    5.2.15          1  x86_64  (远端)
+  34)  deepin-terminal    5.2.16          1  x86_64  (远端)
+  35)  deepin-terminal    5.2.16          1  x86_64  (本地)

输入数字以选择包：17
 deepin-terminal-5...   407.2 KiB  12.8 KiB/s 00:32 [##########################] 100%
正在加载软件包...
警告：正在降级软件包 deepin-terminal (5.2.16-1 => 5.0.4.1-1)
正在解析依赖关系...
正在查找软件包冲突...

软件包 (1)    旧版本  新版本  净变化

deepin-terminal  5.2.16-1  5.0.4.1-1  -0.79 MiB

全部安装大小：   1.91 MiB
净更新大小：  -0.79 MiB

:: 进行安装吗？ [Y/n] 
(1/1) 正在检查密钥环里的密钥                        [##########################] 100%
(1/1) 正在检查软件包完整性                          [##########################] 100%
(1/1) 正在加载软件包文件                            [##########################] 100%
(1/1) 正在检查文件冲突                              [##########################] 100%
(1/1) 正在检查可用存储空间                          [##########################] 100%
:: 正在处理软件包的变化...
(1/1) 正在降级 deepin-terminal                      [##########################] 100%
deepin-terminal 的新可选依赖
    deepin-manual: for help menual
    deepin-shortcut-viewer: for shortcut display [已安装]
:: 正在运行事务后钩子函数...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Updating icon theme caches...
(3/3) Updating the desktop file MIME type cache...
```

**Comment by z966768** [comment]
5.0.x version is old version that we have abandoned maintenance 

https://github.com/linuxdeepin/deepin-terminal-old

The gap between the new version and the old version is too large to add classic mod，if you prefer the old version,welcome to continue to use and maintain the old version of the terminal

**Comment by ghost** [comment]
@z966768 Thanks for your continued work/support of deepin/deepin-termina. I tried the latest version and didn't see any noticable differences in the UI after upgrading.

@amit-gshe downgrade did the trick. I downgraded to 5.0.4.1-1 and have my old terminal back. Thanks so much. I really liked the look and feel of this terminal. I hope in the future the deepin terminal looks more like the old one.

I'm going to close this now as downgrading solved my need for a more asthetically pleasing terminal.

**Comment by ghost** [comment]
Just one more thing. While I'm not completely satisfied with the new terminal look-and-feel downgrading helped me realized I actually prefer the new terminal to the old one. Perhaps we can make some background color changes possible and address the usablility concerns @amit-gshe raised to make the new deeping terminal the favorite terminal for all.
