### ISSUE TITLE
Add multiple Themes to Deepin Terminal again

### ISSUE THREAD

**Issue by Y0ngg4n** [linuxdeepin/deepin-terminal#80]
It was so useful and handy to have the option to switch between multiple Themes in Deepin Terminal.
Please add this option again in Deepin Terminal.

**Comment by ch593030323** [comment]
10 additional themes and the settings of custom themes were added. You can try after updating master branch.

**Comment by Sky-Asher** [comment]
This problem has been unanswered for more than a month and will be closed soon.Thank you for your support!
