### ISSUE TITLE
deepin-terminal 的 tab 偶尔出现序号不连续情况

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/deepin-terminal#84]
## 缺陷描述

deepin-terminal 打开多个 tab 时，本来可以通过 Alt+序号 进行快捷切换。但是偶尔出现个别 tab 无法通过 Alt+序号 切换过去，本应对应的序号被后面的 tab 占据。
## 复现步骤

未知确切重现方法。
### 发行版以及版本

Fedora 30
### 相关的软件包版本

deepin-terminal-3.2.3.1-1.fc30.x86_64
之前的几个版本也有出现过

**Comment by ch593030323** [comment]
I runned terminal in newest master branches, but not saw the above question. U can try.

**Comment by Sky-Asher** [comment]
This problem has been unanswered for more than a month and will be closed soon.Thank you for your support!
