### ISSUE TITLE
深度终端有时候垂直滚动功能失灵

### ISSUE THREAD

**Issue by duanyao** [linuxdeepin/deepin-terminal#85]
## 缺陷描述
深度终端有时候部分tab垂直滚动功能失灵，即无论用触摸板滚动、鼠标滚轮、shift+上下箭头都无法垂直滚动，垂直滚动条也不显示。其中，触摸板滚动、鼠标滚轮会触发历史命令（如同按上下箭头），shift+上下箭头无反应，shift+pageup/pagedown导致输入“;2~”。

这个问题只影响一个或几个深度终端的tab，其它tab可能是没问题的，新打开的tab一般也是没问题的。

## 复现步骤
复现方法不明，但一般几天就会出现一次。

## 期望行为
可以正常垂直滚动。

## 截图
![图片](https://user-images.githubusercontent.com/1684137/64939553-f0028580-d893-11e9-82a6-56145644bf97.png)
如图所示，垂直滚动条不显示。

## 复现环境:
硬件：hp pavilion 14 AL030TX

### 发行版以及版本
deepin 15.11 ，更新到最新。

### 相关的软件包版本
deepin-terminal 3.2.7.1-1+comsta

**Comment by ch593030323** [comment]
看起来是deepin-terminal-gtk的版本，推荐使用deepin-terminal的版本

**Comment by Sky-Asher** [comment]
此问题已超过1个月无人回应，即将被关闭，感谢您的支持！

**Comment by duanyao** [comment]
deepin-terminal 5.4.13-1 又出现了这个问题。系统版本为 deepin 20.3 。

**Comment by ch593030323** [comment]
@duanyao 
请确定是deepin-terminal还是deepin-terminal-gtk
或者提供：软件的关于截图，位置如下图
![image](https://user-images.githubusercontent.com/10093841/146291072-af4e0c1d-c6c9-4e1e-914b-e81c0ba7eb05.png)

**Comment by duanyao** [comment]
确定是 deepin-terminal 。

$ apt policy deepin-terminal
deepin-terminal:
  已安装：5.4.13-1
  候选： 5.4.13-1
  版本列表：
 *** 5.4.13-1 500
        500 https://community-packages.deepin.com/deepin apricot/main amd64 Packages
        100 /var/lib/dpkg/status

$ apt policy deepin-terminal-gtk
N: 无法定位软件包 deepin-terminal-gtk
