### ISSUE TITLE
No roll down when outputing

### ISSUE THREAD

**Issue by scorninpc** [linuxdeepin/deepin-terminal#88]
Is there a way to not scroll down when i'm scrolling screen?

For example, apt are installing somethink, and i'm scrolling to get some past output

Here when i'm scrolling to top, the terminal is autoscrolling me to down

**Comment by ch593030323** [comment]
update the newest master branch, in settings view there are some srolling options for ur issue.
![Screen Capture_select-area_20210915194644](https://user-images.githubusercontent.com/10093841/133427712-43663602-b0a8-4786-b0c5-acb3445e8c8b.png)
