### ISSUE TITLE
[Feat] Font ligature support

### ISSUE THREAD

**Issue by sh4hids** [linuxdeepin/deepin-terminal#9]
Hi guys, thanks for such a nice project (the whole linuxdeepin). I've been using deepin linux for about 1.5 years. Recently I was testing Deepin v20. It's really awesome. 

I was trying to enable font ligature by using [Fantasque Sans Mono Regular Nerd Font](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FantasqueSansMono/Regular/complete/Fantasque%20Sans%20Mono%20Regular%20Nerd%20Font%20Complete.ttf). It didn't work on deepin terminal (v5.0.4.1). But I was able to enable on [Konsole](https://github.com/KDE/konsole) terminal. Below is the screenshot of both:

![DeepinScreenshot_select-area_20200622220439](https://user-images.githubusercontent.com/25576246/85309910-1e715900-b4d5-11ea-9b6b-43420b4bdb55.png)

Do you have any plan to support this feature?

**Comment by BLumia** [comment]
I guess you are using [the legacy GTK/vala version deepin-terminal](https://github.com/linuxdeepin/deepin-terminal-old), the current DTK version probably comes with font ligature support out-of-the-box, maybe you can test it after your distro deliver the new DTK version of deepin-terminal :)

cc @xmuli

**Comment by XMuli** [comment]
![image](https://user-images.githubusercontent.com/33887845/85386781-99d71700-b576-11ea-98f0-3da9b87b1e58.png)

I just changed the name of the warehouse, please take this as the screenshot.

**Comment by sh4hids** [comment]
I can confirm that font ligature works out of the box in [current build](https://github.com/linuxdeepin/deepin-terminal). Here's the screenshot:

![DeepinScreenshot_select-area_20200625095416](https://user-images.githubusercontent.com/25576246/85651538-1e867a00-b6ca-11ea-8466-a5b056213d6d.png)


@BLumia You can close the issue 😀
