### ISSUE TITLE
开启全屏后所有窗口都被置顶了

### ISSUE THREAD

**Issue by ziqiangxu** [linuxdeepin/deepin-terminal#92]
开启两个窗口
- 窗口1 按 `F11` 全屏
- 窗口2 则也被自动置于其他窗口之上

版本 `5.4.0.20`

**Comment by ch593030323** [comment]
uos专业版1031，终端5.4.0.20，接双屏测试，没法发现上面问题
麻烦提供视频或更加详细的步骤

**Comment by Sky-Asher** [comment]
此问题已超过1个月无人回应，即将被关闭，感谢您的支持！

**Comment by ziqiangxu** [comment]
> 
> 
> uos专业版1031，终端5.4.0.20，接双屏测试，没法发现上面问题 麻烦提供视频或更加详细的步骤

抱歉抱歉，没有看到这条回复的邮件提醒。

先前是在deepin上测试的，最新的版本 5.4.13 已经貌似切换了全屏方案（至少样式是发生了变化），已经没有这个问题了
